import React from "react";

export default function TermsSec() {
    return(
        <>
        <section className="policy-sec">
            <div className="content-container">
                <p>By using our site or buying something from us, you are using our "Service" and agreeing to be bound by the terms and conditions and any other policies, terms, and rules linked here or accessible through a hyperlink. All site users must follow these Terms of Service, including but not limited to browsers, suppliers, customers, merchants, or content creators.</p>
                <p>Before you visit or use our website, please read these Terms of Service carefully. If you use any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions of this agreement, you cannot use the website or any of the services. If these Terms of Service are seen as an offer, only these Terms of Service can be accepted.</p>
                <p>The Terms of Service also apply to any new tools or features added to the shop. You can always find the latest version of the Terms of Service on this page. We reserve the right to update, change, or eliminate any part of these Terms of Service by making changes or updates to our website. You should check this page often to see if anything has changed. You agree if you keep using or going to the website after posting these changes.</p>
                <h1>SEGMENT 1 - TERMS OF AN ONLINE COMPANY</h1>
                <p>By agreeing to these Terms of Service, you confirm that you are at least the legal age of majority in your state or province of residence or that you are at least the legal age of majority in your state or province of residence and have permitted us to let any of your minor dependents use this site.</p>
                <p>You cannot use our products for anything illegal or against the law, and you cannot break any local laws by using the Service. You cannot send any worms, viruses, or other code that could cause trouble. If you break the rules, your Services will be turned off immediately.</p>
                <h1>SEGMENT 2: ALL THE OTHER RULES</h1>
                <p>We can refuse to help anyone at any time and for any reason. You agree that your content (except for credit card information) may be sent without encryption and may involve (a) transmissions across different networks and (b) changes to meet and adapt to the technical requirements of connection networks or devices. It is always encrypted whenever credit card information is sent over the network.</p>
                <p>Without our permission, you promise not to copy, sell, resell, or make money off any part of the Service, how the Service is used, how to access the Service or any contact on the website where the service is offered. The headers in this agreement are just there to make it easier to read. They have nothing to do with the Terms.</p>
                <h1>SEGMENT 3: Precise, Accurate, and On-Time Data</h1>
                <p>We are not responsible if the information on this site is not correct, complete, or up to date. The information on this website is just for general knowledge. It would be best if you did not rely on it or use it as your only source of information without looking at primary sources that are more accurate, complete, or up-to-date.</p>
                <p>This website might have information about the past. By definition, information from the past is out of date and is only given to help you. We reserve the right to change the information on this site at any time, but we are not required to keep any of the information on this site current. You agree that it is your job to keep up with any changes we make to our website.</p>
                <h1>SEGMENT 4 - SERVICE AND RATES ADJUSTMENTS</h1>
                <p>Our prices can change at any time without notice. We reserve the right to change or end the Service (or any part of it or its content) at any time and without warning. We will not have to answer you or anyone else if the Service is changed, priced differently, put on hold, or stopped.</p>
                <h1>SEGMENT 5 - SERVICES AND PRODUCTS</h1>
                <p>There may be things or services that can only be bought or sold on the website. There may not be many of these items or services, and you can only return or exchange them if you follow our Return Policy. We have done everything we can to ensure that the colors and pictures of our items in the shop are as accurate as possible. We cannot promise that the colors you see on your computer screen are correct.</p>
                <p>We have the right, but not the obligation, to limit the sale of our goods or services to certain people, places, or legal systems. We can use this right on a case-by-case basis. We keep the right to limit how much of our goods or services you can buy. All product descriptions and prices can change at any time without notice, and it is up to us to decide what those changes are. We have the right to take any product off the market at anytime. Any offer for a good or service on this site is void where it is illegal.</p>
                <p>We do not promise that the quality of any products, services, information, or other content you buy or get access to will meet your expectations. We also do not promise that any mistakes in the Service will be fixed.</p>
                <h1>SEGMENT 6: FEES AND THE SECURITY OF ACCOUNT INFORMATION</h1>
                <p>We can turn down any order that is placed with us. We reserve the right to limit or cancel the number of items that can be bought by one person, one household, or one order. These rules may apply to orders made by or under the same customer account, credit card, billing address, or shipping address. If we change or cancel an order, we may try to contact you at the e-mail address, billing address, or phone number you gave us when you made the transaction. We have the right to limit or turn down orders that look like they are from dealers, resellers, or distributors.</p>
                <p>You agree to give us up-to-date, full, and correct account and purchase information for any purchases you make on our site. You agree to keep your account and other information, like your email address, credit card numbers, and expiration dates, up to date so we can process transactions and get in touch with you as needed.</p>
                <h1>SEGMENT 7: ADDITIONAL RESOURCES</h1>
                <p>We may give you access to tools that do not belong to us or that we have nothing to do with. You understand and agree that we offer these tools "as is" and "as available" without any warranty, promise, or terms and any endorsement. We do not take any responsibility for your use of third-party tools that you can choose to use.</p>
                <p>Any use of optional tools on the site is at your own risk and choice, and you should make sure you understand and agree with the terms under which the third-party provider offers the tools (s). We might add more services or features to the website at some point in the future. Any new features or services will be subject to these Terms of Service.</p>
                <h1>SEGMENT 9: REVIEWS, COMMENTS, AND OTHER USER SUBMISSIONS</h1>
                <p>Suppose you send us creative ideas, suggestions, proposals, plans, or other materials (collectively called "comments") online, by email, mail, or any other way. In that case, you agree that we can edit, copy, publish, distribute, translate, and otherwise use any comments you send us in any way, at any time, and without restrictions. We do not have to keep any comments secret, pay anyone for any comments, or respond to any, and we never will.</p>
                <p>We may, but are not required to, monitor, edit, or delete content that we think is illegal, offensive, threatening, libelous, defamatory, pornographic, obscene, or otherwise offensive or violates the intellectual property of any party or our Terms of Service.</p>
                <p>We may, but are not required to, monitor, edit, or delete content that we think is illegal, offensive, threatening, libelous, defamatory, pornographic, obscene, or otherwise offensive or violates the intellectual property of any party or our Terms of Service.</p>
                <h1>SEGMENT 10 - Private Info</h1>
                <p>Our Privacy Policy says you can use the site to give us personal information.</p>
                <h1>SEGMENT 11 – MISTAKES, INACCURACIES, AND MISSTATEMENTS</h1>
                <p>There may be typos, mistakes, or omissions in the descriptions, prices, promotions, offers, shipping costs, transit times, and availability of products on our website or in the Service from time to time. We reserve the right to fix any mistakes, inaccuracies, or omissions at any time and without notice, as well as to change or update information or cancel orders if any information in the Service or on any website connected to it is wrong (including after you have submitted your order).</p>
                <p>We do not promise to update, change, or clarify anything in the Service or on any linked website, including price information unless the law says we have to. There is no specific update or refresh date in the Service or on any website that links to it. This should not mean that all of the information in the Service or on any linked website has been changed or updated.</p>
                <h1>SEGMENT 12 - PROHIBITED APPLICATIONS</h1>
                <p>In addition to the other rules in terms of Service, you are not allowed to use the site or its content: (a) for any illegal purpose; (b) to get other people to do illegal things or operate illegal things; (c) to break any global, federal, provincial, or state rules, laws, regulations, or municipal ordinances; (d) to invade or offend our rights to intellectual property or the rights to the intellectual property of others; and (e) to harass, abuse, offend, damage, or harm another person We can stop you from using the Service or any related website if you break any of the rules about what you cannot do with it.</p>
                <h1>SEGMENT 13 - WARRANTY DISCLAIMER; LIABILITY LIMITATION</h1>
                <p>We do not promise, represent, or guarantee that you will be able to use our service without interruption, on time, securely, or without making mistakes.</p>
                <p>We cannot promise that the information you get from using the service will be correct or reliable.</p>
                <p>You agree that we can stop the service for an undetermined amount of time or end it at any time without telling you first.</p>
                <p>You agree that using the service or not being able to use it is completely at your own risk. The service and all products and services delivered to you through the service are provided "as is" and "as available" for your use without any express or implied representations, warranties, or conditions of any kind, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
                <p>Arabic Wave, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers, or licensors are not responsible for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, but not limited to, lost profits, lost revenue, lost savings, loss of data, replacement costs, or other similar damages, whether based in contract, tort (including negligence), or otherwise. Because some states or countries don't let you exclude or limit your responsibility for indirect or accidental damages, our liability will be limited to the fullest extent allowed by law in those places.</p>
                <h1>SEGMENT 14 – INDEMNIFICATION</h1>
                <p>You agree to protect, uphold, and hold harmless Novaone Consulting Services LLP and our parent, subsidiary companies, associates, partners, executives, directors, representatives, contractors, rights holders, service providers, sub-contractors, suppliers, trainees, and staff from any claim or request, including reasonable attorney's fees, made by any third party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference or your violation of any law or the rights of a third party.</p>
                <h1>SEGMENT 15 – SEVERABILITY</h1>
                <p>If any part of these Terms of Service is found to be illegal, void, or unenforceable, it will be enforced to the fullest extent allowed by law, and the part that can't be executed will be considered to be cut out of these Terms of Service. This won't change the validity or enforceability of the other parts.</p>
                <h1>SEGMENT 16 – TERMINATION</h1>
                <p>For any reason, the responsibilities and liabilities the parties had before this agreement ended will still be in effect.</p>
                <p>These Terms of Service will stay in place until you or we decide to end them. You can end these Terms of Service anytime by telling us you don't want to use our services anymore or by not using our website anymore.</p>
                <p>If in our sole judgment, you don't follow any of the terms or rules in these Terms of Service, or if we think you haven't, we can end this agreement at any time without notice, and you'll still be responsible for all payments up to and including the date of termination. We can also stop you from using our Services.</p>
                <h1>SEGMENT 17 - COMPLETE AGREEMENT</h1>
                <p>If we don't use or enforce a right or rule in these Terms of Service, that doesn't mean we've given up on that right or rule.</p>
                <p>These Terms of Service and any policies or operating rules we post on this site or with The Service are the whole agreement between you and us. They control how you use The Service and take the place of any agreements, communications, or proposals, written or spoken, between you and us. If people have different ideas about how to read these Terms of Service, that shouldn't be held against the person who wrote them.</p>
                <h1>SEGMENT 18: CHANGES TO THE TERMS OF SERVICE</h1>
                <p>On this page, you can always find the latest version of the Terms of Service.</p>
                <p>We hold the right to update, change, or replace any part of these Terms of Service at any time. We will post updates and changes to our website when we do this. You should check our website often to see if anything has changed. If you keep using our website or the Service after any changes to these Terms of Service have been posted, you agree to the changes.</p>

            </div>
        </section>
        </>
    )
}